name: "Run builds (mybee)"
on: push

permissions:
  packages: write

jobs:
  linux:
    name: FreeBSD build on node ${{ matrix.node_version }}
    runs-on: [freebsd]
    steps:
    - name: checkout sources
      uses: convectix/checkout@master
    - name: git
      run: cat .git/config
    - name: ls
      run: ls -la
    - name: pwd
      run: pwd
    - name: uname
      run: uname -a
    - name: iostat
      run: /usr/sbin/iostat 1 600
