name: "Run builds (mybee)"
on: push

permissions:
  packages: write

jobs:
  linux:
    name: Build on node ${{ matrix.node_version }}
    runs-on: self-hosted
    steps:
    - name: checkout sources
      uses: convectix/checkout@master
    - name: git
      run: cat .git/config
    - name: ls
      run: ls -la /
    - name: pwd
      run: pwd
    - name: file
      run: file -s README.md
    - name: uname
      run: uname -a
    - name: iostat
      run: /usr/sbin/iostat -c 100
